/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { UUPSProxiable__factory } from "./UUPSProxiable__factory";
export { UUPSProxy__factory } from "./UUPSProxy__factory";
